### ISSUE TITLE
ngrok not starting

### ISSUE THREAD

**Issue by porcupiney** [mr-manuel/venus-os_ngrok#1]
Hi,
I have installed this, but it is not starting a connection to ngrok.

But when I run the ngrok tcp 22 command from an ssh login to the Pi, it works fine.

I think there is something wrong with the way venus-os_ngrok.py starts ngrok using nohup.

Dave

**Comment by mr-manuel** [comment]
Can you post the output of the log?

**Comment by porcupiney** [comment]
cat /var/log/venus-os_ngrok/current
@40000000646cefe001dfe19c INFO:root:Value "Enabled" changed from "1" to "0"
@40000000646cefe0068286dc INFO:root:pid: False
@40000000646cefe0068a473c INFO:root:ngrok was not running
@40000000646cefeb02a2e764 INFO:root:Value "Enabled" changed from "0" to "1"
@40000000646cefeb07208814 INFO:root:pid: False
@40000000646cefeb0728cd44 INFO:root:Start ngrok (tcp/22)...
@40000000646cefeb0730918c INFO:root:nohup /data/venus-os_ngrok/ngrok tcp 22 --log=false > /tmp/ngrok.out &
@40000000646cefee1bc33b2c 
@40000000646cefee1bc54e6c ERROR:  failed to start tunnel: TCP tunnels are only available to registered users.
@40000000646cefee1bc561f4 ERROR:  Sign up for free at: https://dashboard.ngrok.com/signup
@40000000646cefee1bc57194 ERROR:  
@40000000646cefee1bc57964 ERROR:  If you have already signed up, make sure your authtoken is installed.
@40000000646cefee1bc58904 ERROR:  Your authtoken is available on your dashboard: https://dashboard.ngrok.com/get-started/your-authtoken
@40000000646cefee1bc5a074 ERROR:  
@40000000646cefee1bc5a844 ERROR:  ERR_NGROK_302
@40000000646cefee1bc615a4 ERROR:

and 
root@raspberrypi2:~# cat /tmp/ngrok.out 
NAME:
  tcp - start a TCP tunnel

USAGE:
  ngrok tcp [address:port | port] [flags]

DESCRIPTION: 
  Starts a tunnel which forwards all TCP traffic on a public port to a local
  address. This is extremely useful for exposing services that run non-HTTP
  traffic (ssh, sip, rdp, game servers, etc).

  A TCP tunnel binds a public address on the remote ngrok server. Any
  services which require a stable public address should use the
  --remote-addr option. ngrok requires that you reserve a TCP tunnel
  address for your account before you can use it.

TERMS OF SERVICE: https://ngrok.com/tos

EXAMPLES: 
  # forward a port to your local ssh server
  ngrok tcp 22

  # expose an RDP server on a specific public address that you reserved
  ngrok tcp --remote-addr=1.tcp.ngrok.io:27210 3389

OPTIONS:
      --authtoken string     ngrok.com authtoken identifying a user
      --cidr-allow strings   reject connections that do not match the given CIDRs
      --cidr-deny strings    reject connections that match the given CIDRs
      --config strings       path to config files; they are merged if multiple
  -h, --help                 help for tcp
      --log string           path to log file, 'stdout', 'stderr' or 'false' (default "false")
      --log-format string    log record format: 'term', 'logfmt', 'json' (default "term")
      --log-level string     logging level: 'debug', 'info', 'warn', 'error', 'crit' (default "info")
      --proxy-proto string   version of proxy proto to use with this tunnel, empty if not using
      --region string        ngrok server region [us, eu, au, ap, sa, jp, in] (default "us")
      --remote-addr string   bind remote address (requires you reserve an address)

**Comment by mr-manuel** [comment]
Have you inserted the `authtoken`? [ERR_NGROK_302](https://ngrok.com/docs/errors/err_ngrok_302/) is the error code for a missing `authtoken`.

You can also verify the `authtoken` with the `dbus-spy`.

**Comment by porcupiney** [comment]
Yes - I used dbus -y com.victronenergy.settings /Settings/Services/Ngrok/AuthToken GetValue and it matched my actual authtoken

**Comment by mr-manuel** [comment]
1. Are you using a Raspberry Pi, a Cerbo GX or another device?
2. Which Venus OS are you using?

Could you check with which user ngrok is started, if you enable it in the GUI? Probably the `authtoken` is not saved correctly.

**Comment by mr-manuel** [comment]
Can you also check, if your `authtoken` was set in `/.config/ngrok/ngrok.yml` or `/data/home/root/.config/ngrok/ngrok.yml`?

**Comment by mr-manuel** [comment]
I just installed a fresh Venus OS `v2.94` and I had no issues on a Raspberry Pi 4. After trying to upgrade to `v3.00~42` I got the same error. This is because the configuration get deleted, you have to change a letter from the `authtoken` and then back. This will be fixed in the next release.

**Comment by porcupiney** [comment]
Hi,
Well - that has allowed it to start. So it works. BUT it seems that the permissions in /services/venus-os_ngrok/run and .../log/run do not survive a reboot - so I get it working indoors, but when I reboot back in my campervan, the service is not running...
Dave

**Comment by mr-manuel** [comment]
Did you install version `v0.0.2`?
