### ISSUE TITLE
only white screen after install

### ISSUE THREAD

**Issue by JTHanken** [mr-manuel/venus-os_ngrok#2]
Hi, yesterday I installed venus os ngrok and after the restart I became only a full white screen.
No text, symbols or else. I´ve tried it over remote console and I went to my mobile home, the touchdisplay is also a white screen.
My version of venus os is 2.89. GuiMods the latest version.
Has anybody the same problem and solved it before?
All funktions of the system are given via vrm portal, just the display is white.

**Comment by mr-manuel** [comment]
Have you SSH access?

**Comment by JTHanken** [comment]
Yes.
And so I did it. Uninstall via SSH. Now all is fine again. Thanks.

Do you know why my display ist going to white after Install?


Am 18. Juni 2023 06:14:21 MESZ schrieb Manuel ***@***.***>:

**Comment by mr-manuel** [comment]
I just released a new version. Please try that.
