### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by porcupiney** [mr-manuel/venus-os_ngrok#4]
hi,

with venus version 3.00 there is missing files

prolly works with 3.10-8, no longer available

with current latest 3.10-9 it fails to install...

cheers dave (from my phone

**Comment by mr-manuel** [comment]
I opened an issue in https://github.com/kwindrem/SetupHelper/issues/52 for more informations.

**Comment by mr-manuel** [comment]
Could you please try the latest version?
