### ISSUE TITLE
Feature Request: Add static domain

### ISSUE THREAD

**Issue by keeskode** [mr-manuel/venus-os_ngrok#6]
It's possible within Ngrok to use a static domain - even with the free account now. This is great as then you don't have rotating addresses anymore.

For testing; I have manually added the .py file to change the command to add --domain=[mystaticdomain] (see here: https://ngrok.com/blog-post/free-static-domains-ngrok-users) and it works.

It's not possible however to set the static domain in the VRM GUI settings page. Would be great if this can also be supported by the VRM GUI, like you can change the port or protocol.

**Comment by mr-manuel** [comment]
I added it, but keep in mind, that it doesn't work with `TCP`.

> Domains are endpoints that accept HTTP, HTTPS and TLS traffic. Claim one free static domain per user or upgrade to paid to use a domain of your choice. [Read more about domains in our docs.](https://ngrok.com/docs/network-edge/domains-and-tcp-addresses/?ref=dashboard-domains)[This guide walks you through setting up a custom domain.](https://ngrok.com/docs/guides/how-to-set-up-a-custom-domain/)
